#ifndef DEFINE_HPP
# define DEFINE_HPP

#define DEFAULT_CONFIG_FILE_PATH "default.config"
#define BUFFER_SIZE 100
#define INIT_FD_MAX 512
#define KEEP_ALIVE_LIMIT 5 // TODO 갱신처리 안됬음!
#define SELECT_TIMEOUT_SEC 10
#define SELECT_TIMEOUT_USEC 0

#define BUFIZE_HTMLFILE 300

enum TYPE_HTML
{
	ERROR_HTML,
	INDEX_HTML,
	ANY_FILE
};

#endif
