#pragma once

#include "../base_headers/Buffer.hpp"
#include "../base_headers/Cgi.hpp"
#include "../base_headers/Cgi.hpp"
#include "../base_headers/Client.hpp"
#include "../base_headers/Config.hpp"
#include "../base_headers/ConfigWebserver.hpp"
#include "../base_headers/FdSet.hpp"
#include "../base_headers/Http.hpp"
#include "../base_headers/Method.hpp"
#include "../base_headers/Path.hpp"
#include "../base_headers/Server.hpp"
#include "../base_headers/Socket.hpp"
#include "../base_headers/Url.hpp"
#include "../base_headers/utils.hpp"
#include "../base_headers/UtilsTemplate.hpp"
#include "../base_headers/Webserver.hpp"
