on: pull_request
name: Pull Request
jobs:
  test:
    name: Run tests
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@master
    - name: Test
      uses: skx/github-action-tester@master
      with:
        script: .github/test.sh
